// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Volumes/D/Node/SEHC/msalReactNative/msalRnNew/node_modules/react');
var { Component } = React;
var ReactNative = require('/Volumes/D/Node/SEHC/msalReactNative/msalRnNew/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('msalRnNew', appParameters);
});
require('/Volumes/D/Node/SEHC/msalReactNative/msalRnNew/index.js');